//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsEmriBaslatma_DataAccesLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IS_EMIRLERI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IS_EMIRLERI()
        {
            this.IS_EMRI_KALEMLERI = new HashSet<IS_EMRI_KALEMLERI>();
        }
    
        public int IS_EMRI_ID { get; set; }
        public Nullable<int> OLUSTURAN_ID { get; set; }
        public string IS_EMRI_NO { get; set; }
        public string URUN_ADI { get; set; }
        public string URUN_KODU { get; set; }
        public string Toplam_Siparis_Miktari { get; set; }
        public string Temel_Olcu_Birimi { get; set; }
        public string TARIH { get; set; }
        public string IMAGE { get; set; }
        public string TEKLI_SEVIYE { get; set; }
        public string COKLU_SEVIYE { get; set; }
        public string STATU { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<System.DateTime> IS_EMRI_BITIS_TARIHI { get; set; }
    
        public virtual KULLANICILAR KULLANICILAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IS_EMRI_KALEMLERI> IS_EMRI_KALEMLERI { get; set; }
    }
}
