//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsEmriBaslatma_DataAccesLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IS_EMRI_KALEMLERI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IS_EMRI_KALEMLERI()
        {
            this.SAPMA = new HashSet<SAPMA>();
        }
    
        public int ID { get; set; }
        public Nullable<int> is_EMRI_ID { get; set; }
        public string IS_EMRI_NO { get; set; }
        public string KAYNAK { get; set; }
        public string STOK_KODU { get; set; }
        public string STOK_ISMI { get; set; }
        public string MAL_GRUBU { get; set; }
        public string OLCU_BIRIMI { get; set; }
        public string MIKTAR { get; set; }
        public string URUN_BASINA_MIKTAR { get; set; }
        public string BOLD { get; set; }
        public string KULLANILAN_MIKTAR { get; set; }
        public string ALTERNATIF_URUN { get; set; }
        public string SAPMA_NEDENI { get; set; }
        public Nullable<bool> SAPMA_DURUM { get; set; }
        public string STATU { get; set; }
    
        public virtual IS_EMIRLERI IS_EMIRLERI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAPMA> SAPMA { get; set; }
    }
}
