//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsEmriBaslatma_DataAccesLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICILAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KULLANICILAR()
        {
            this.IS_EMIRLERI = new HashSet<IS_EMIRLERI>();
        }
    
        public int ID { get; set; }
        public string SICIL_NO { get; set; }
        public string SIFRE { get; set; }
        public Nullable<int> ROL_ID { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public Nullable<bool> KULLANICI_LOG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IS_EMIRLERI> IS_EMIRLERI { get; set; }
    }
}
